version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/stock_exchange
      - SECRET_KEY=your-secret-key-here
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    volumes:
      - .:/api
      - /api/__pycache__
      - /api/.pytest_cache
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /api

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock_exchange
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
