version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: stock_exchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      cache_from:
        - python:3.11-slim
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/stock_exchange
    volumes:
      - ./api:/app/api:delegated
      - ./api/migrations:/app/api/migrations:delegated
      - api_python_cache:/root/.cache/pip
    tmpfs:
      - /tmp
      - /var/tmp

volumes:
  postgres_data:
  api_python_cache: 