version: "3.7"

services:
  app:
    image: {{ env.API_IMAGE }}
    restart: always
    command: opentelemetry-instrument --service_name sstock uvicorn api.main:app --host 0.0.0.0 --port 80 --proxy-headers --forwarded-allow-ips="*"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.2-bookworm
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock_exchange
    healthcheck:
          test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d stock_exchange'" ]
          interval: 10s
          timeout: 3s
          retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - "5050:80"
      depends_on:
        - db

  nginx:
      container_name: nginx
      image: {{ env.NGINX_IMAGE }}
      ports:
        - "80:80"
        - "443:443"
      restart: always
      volumes:
        - /certs/nginx.crt:/etc/nginx/certs/certificate.crt
        - /certs/nginx.key:/etc/nginx/certs/certificate.key


volumes:
  postgres_data:
