version: "3.7"

services:
  app:
    image: {{ env.API_IMAGE }}
    restart: always
    command: >
      sh -c "alembic upgrade head &&  uvicorn app.main:app --host 0.0.0.0 --port 80 --workers 8"
    environment:
    - DATABASE_URL=postgresql://exchange:exchange@db:5432/exchange
    - SECRET_KEY=dev-secret-key
    - ADMIN_API_KEY=key-81ce43a7-14fd-45de-9b99-82218228935a
    - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.2-bookworm
    restart: always
    environment:
      - POSTGRES_USER=exchange
      - POSTGRES_PASSWORD=exchange
      - POSTGRES_DB=exchange
    healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U exchange" ]
          interval: 10s
          timeout: 3s
          retries: 3
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - "5050:80"
      depends_on:
        - db

  nginx:
      container_name: nginx
      image: {{ env.NGINX_IMAGE }}
      ports:
        - "80:80"
        - "443:443"
      restart: always
      volumes:
        - /certs/nginx.crt:/etc/nginx/certs/certificate.crt
        - /certs/nginx.key:/etc/nginx/certs/certificate.key
      depends_on:
        app:
          condition: service_started

  jaeger:
      image: jaegertracing/jaeger:2.0.0
      container_name: jaeger
      environment:
        - COLLECTOR_OTLP_ENABLED=true
      ports:
        - "5778:5778"
        - "16686:16686"
        - "4317:4317"
        - "4318:4318"
        - "14250:14250"
        - "14268:14268"
        - "9411:9411"
      command:
        - --set
        - receivers.otlp.protocols.http.endpoint=0.0.0.0:4318
        - --set
        - receivers.otlp.protocols.grpc.endpoint=0.0.0.0:4317
      restart: always


volumes:
  postgres_data2:
